/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package get.it.back;

import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pranjal Paliwal
 */
public class FindLost extends javax.swing.JFrame {

    /**
     * Creates new form FindLost
     */
    String person = "";
    String pnumber = "";

    public FindLost() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        articleNameTf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CategoryCB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LocationTf = new javax.swing.JTextField();
        brandTf = new javax.swing.JTextField();
        LostDateTf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultList = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        confirmButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel8.setText("jLabel8");

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Find a Lost Item");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 734, 69));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Article Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 91, 145, 23));

        articleNameTf.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getContentPane().add(articleNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 93, 243, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Select Category");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 120, 179, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Brand Name (Optional)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 148, 265, 25));

        CategoryCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        CategoryCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Identity Proof", "Watch", "Mobile Phone", "Wallet/Purse", "Bags", "Others" }));
        CategoryCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryCBActionPerformed(evt);
            }
        });
        getContentPane().add(CategoryCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 121, 243, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Lost Date (Optional) in DD-MM-YY Format");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 179, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Location where you lost it");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 207, 265, 25));

        LocationTf.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        LocationTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationTfActionPerformed(evt);
            }
        });
        getContentPane().add(LocationTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 210, 243, -1));

        brandTf.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getContentPane().add(brandTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 151, 243, -1));

        LostDateTf.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        LostDateTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LostDateTfActionPerformed(evt);
            }
        });
        getContentPane().add(LostDateTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 180, 243, -1));

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 153));
        jButton1.setText("Search for Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 250, 225, -1));

        ResultList.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        ResultList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ResultList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ResultListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ResultList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 343, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Found Results");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 304, 218, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("More Details");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 304, 280, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 340, 258, 133));

        confirmButton.setBackground(new java.awt.Color(255, 102, 0));
        confirmButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 153));
        confirmButton.setText("Confirm Item");
        confirmButton.setEnabled(false);
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 491, 129, -1));

        jButton3.setBackground(new java.awt.Color(255, 102, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 153));
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 491, 71, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/get/it/back/still_alive_1920x1080.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ArticleName = articleNameTf.getText();
        String Category = (String) CategoryCB.getSelectedItem();
        String ArticleBrand = brandTf.getText();
        String Location = LocationTf.getText();
        String LostDate = LostDateTf.getText();
        try {

            Class.forName("com.mysql.jdbc.Driver");
            String uid = "root";
            String pwd = "clever";
            String dbURL = "jdbc:mysql://localhost/getitback";
            Connection conn = DriverManager.getConnection(dbURL, uid, pwd);
            Statement statement = conn.createStatement();

            ArticleName = ArticleName.replaceAll("'", "''");
            //Category = Category.replaceAll("'", "''");
            ArticleBrand = ArticleBrand.replaceAll("'", "''");
            String query = "SELECT * from foundItems where ArticleName like '%" + ArticleName + "%' and Category ='" + Category + "'";
            if (!ArticleBrand.equals("")) {
                query = query + "and ArticleBrand like '%" + ArticleBrand + "%'";
            } else {
                ArticleBrand = "Not Specified";
            }

            System.out.println(query);
            ResultSet rs = statement.executeQuery(query);

            DefaultListModel listModel = new DefaultListModel();
            if (!rs.next()) {
                int response = JOptionPane.showConfirmDialog(this, "Item was not found. Try Another Search?", "Select a Choice", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (response == JOptionPane.NO_OPTION) {
                    int response2 = JOptionPane.showConfirmDialog(this, "Do you want to get notified when item is found?", "Select a Choice", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (response2 == JOptionPane.YES_OPTION) {
                        JPanel panel = new JPanel();
                        JLabel details = new JLabel("Edit Details");
                        Font titleFont = new Font("Segoe UI", Font.PLAIN, 24);
                        details.setFont(titleFont);
                        JLabel articleName = new JLabel("Article Name");
                        JTextField articleNameTf = new JTextField();
                        articleNameTf.setText(ArticleName);
                        JLabel articleBrand = new JLabel("Article Brand");
                        JTextField articleBrandTf = new JTextField();
                        articleBrandTf.setText(ArticleBrand);
                        JLabel date = new JLabel("Lost Date");
                        JTextField dateTf = new JTextField();
                        dateTf.setText(LostDate);
                        JLabel LostLocation = new JLabel("Lost Location");
                        JTextField LostLocationTf = new JTextField();
                        LostLocationTf.setText(Location);
                        JLabel Name = new JLabel("Your Name");
                        JTextField NameTf = new JTextField();
                        LostLocationTf.setText(Location);
                        JLabel Number = new JLabel("Your Phone Number");
                        JTextField NumberTf = new JTextField();
                        LostLocationTf.setText(Location);
                        panel.add(details);
                        panel.add(articleName);
                        panel.add(articleNameTf);
                        panel.add(articleBrand);
                        panel.add(articleBrandTf);
                        panel.add(date);
                        panel.add(dateTf);
                        panel.add(LostLocation);
                        panel.add(LostLocationTf);
                        panel.add(Name);
                        panel.add(NameTf);
                        panel.add(Number);
                        panel.add(NumberTf);

                        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));

                        String[] options = new String[]{"OK", "Cancel"};
                        int option = JOptionPane.showOptionDialog(this, panel, "Edit Deatails",
                                JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                                null, options, options[1]);

                        String nArticleName = articleNameTf.getText();
                        String nArticleBrand = articleBrandTf.getText();
                        String nDate = dateTf.getText();
                        String nLocation = LostLocationTf.getText();
                        String nName = NameTf.getText();
                        String nNumber = NumberTf.getText();
                        long randID = System.currentTimeMillis();
                        int a = 0;
                        for (int i = 0; i < 5; i++) {
                            a = a * 10 + new Random().nextInt(100);
                        }
                        randID /= a;

                        String addQuery = "Insert into LostItems values (" + randID + ",'" + nArticleName + "','" + nArticleBrand + "','" + Category + "','" + nDate + "','" + nLocation + "','" + nName + "'," + nNumber + ")";

                        System.out.println(addQuery);

                        statement.executeUpdate(addQuery);
                        JOptionPane.showMessageDialog(null, "You will be notified if the item is found on your number " + nNumber + " .Note down your ItemId:" + randID);

                    }
                }
            } else {
                String articleName = rs.getString("ArticleName");
                listModel.addElement(articleName);
                while (rs.next()) {
                    articleName = rs.getString("ArticleName");
                    listModel.addElement(articleName);
                }

                ResultList.setModel(listModel);
                ResultList.setEnabled(true);

                rs.close();
                statement.close();
                conn.close();

            }
            confirmButton.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(FindLost.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FindLost.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LocationTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationTfActionPerformed

    private void ResultListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ResultListValueChanged
        // TODO add your handling code here:

        String ArticleName = ResultList.getSelectedValue();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String uid = "root";
            String pwd = "clever";
            String dbURL = "jdbc:mysql://localhost/getitback";
            Connection conn = DriverManager.getConnection(dbURL, uid, pwd);
            Statement statement = conn.createStatement();

            String query = "Select * from foundItems where ArticleName like '%" + ArticleName + "%'";

            ResultSet rs = statement.executeQuery(query);
            rs.next();
            String articleName = rs.getString("ArticleName");
            String articleBrand = rs.getString("ArticleBrand");
            String category = rs.getString("Category");
            String FoundDate = rs.getString("FoundDate");
            String FoundLocation = rs.getString("FoundLocation");
            person = rs.getString("PersonToContact");
            pnumber = rs.getString("ContactNumber");

            jTextArea1.setText("");

            jTextArea1.append("Name: " + articleName + "\n");
            jTextArea1.append("Article Brand: " + articleBrand + "\n");
            jTextArea1.append("Category:" + category + "\n");
            jTextArea1.append("Found Date: " + FoundDate + "\n");
            jTextArea1.append("Found Location: " + FoundLocation + "\n");

            confirmButton.setEnabled(true);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReportFound.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ReportFound.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ResultListValueChanged

    private void LostDateTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LostDateTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LostDateTfActionPerformed

    private void CategoryCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoryCBActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Do you confirm of the Ownership of the belongings?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {
            System.out.println("No button clicked");
        } else if (response == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Your Lost Items are with "+ person + ". Contact Number:" + pnumber);
        } else if (response == JOptionPane.CLOSED_OPTION) {
            System.out.println("JOptionPane closed");
        }

    }//GEN-LAST:event_confirmButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        brandTf.setText("");
        CategoryCB.setSelectedIndex(0);
        confirmButton.setEnabled(false);
        LostDateTf.setText("");
        LocationTf.setText("");
        DefaultListModel listModel = new DefaultListModel();
        ResultList.setModel(listModel);
        articleNameTf.setText("");
        person = "";
        pnumber = "";
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindLost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindLost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindLost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindLost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindLost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CategoryCB;
    private javax.swing.JTextField LocationTf;
    private javax.swing.JTextField LostDateTf;
    private javax.swing.JList<String> ResultList;
    private javax.swing.JTextField articleNameTf;
    private javax.swing.JTextField brandTf;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
