/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package get.it.back;

import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Pranjal Paliwal
 */
public class ReportFound extends javax.swing.JFrame {

    
    String person = "";
    String pnumber = "";
    
    /**
     * Creates new form ReportFound
     */
    public ReportFound() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        articleNameTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CategoryCB = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        BrandNameTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DateTf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        LocationTf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NameTf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        mNumberTf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ConfirmButton = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Report A Found Item");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, 740, 45));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Article Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 74, 195, -1));

        articleNameTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(articleNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 75, 350, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select Category");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 102, 179, -1));

        CategoryCB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CategoryCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Identity Proof", "Watch", "Mobile Phone", "Wallet/Purse", "Bags", "Others" }));
        getContentPane().add(CategoryCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 103, 350, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Brand Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 130, 179, -1));

        BrandNameTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(BrandNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 131, 350, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Found Date (DD-MM-YY)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 158, 200, -1));

        DateTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(DateTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 159, 350, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Found Location");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 186, 179, -1));

        LocationTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(LocationTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 187, 350, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Enter your Contact Details");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 226, 563, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 266, 209, -1));

        NameTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(NameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 267, 351, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mobile Number");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 294, 209, -1));

        mNumberTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(mNumberTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 295, 351, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 322, 166, -1));

        ResultList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ResultList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ResultListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ResultList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 401, 359, 107));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 401, 340, 107));

        ConfirmButton.setBackground(new java.awt.Color(255, 153, 0));
        ConfirmButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ConfirmButton.setText("Confirm Button");
        ConfirmButton.setEnabled(false);
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 528, 140, -1));

        Reset.setBackground(new java.awt.Color(255, 153, 0));
        Reset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 526, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("More Details");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 365, 353, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Found Results");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 365, 369, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/get/it/back/summer_lights_wallpaper_hd_by_jelinjer-d7bl33e (1).jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ArticleName = articleNameTf.getText();
        String Category = (String) CategoryCB.getSelectedItem();
        String BrandName = BrandNameTf.getText();
        String Date = DateTf.getText();
        String Location = LocationTf.getText();
        String pName = NameTf.getText();
        String mNumber = mNumberTf.getText();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            String uid = "root";
            String pwd = "clever";
            String dbURL = "jdbc:mysql://localhost/getitback";
            Connection conn = DriverManager.getConnection(dbURL, uid, pwd);
            Statement statement = conn.createStatement();

            ArticleName = ArticleName.replaceAll("'", "''");
            //Category = Category.replaceAll("'", "''");
            BrandName = BrandName.replaceAll("'", "''");
            String query = "SELECT * from lostItems where ArticleName like '%" + ArticleName + "%' and Category ='" + Category + "'";
            if (!BrandName.equals("")) {
                query = query + "and ArticleBrand like '%" + BrandName + "%'";
            } else {
                BrandName = "Not Specified";
            }

            System.out.println(query);
            ResultSet rs = statement.executeQuery(query);

            DefaultListModel listModel = new DefaultListModel();
            if (!rs.next()) {
                int response = JOptionPane.showConfirmDialog(this, "Item was not found. Try Another Search?", "Select a Choice", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (response == JOptionPane.NO_OPTION) {
                    int response2 = JOptionPane.showConfirmDialog(this, "Do you want to get notified when owner is found?", "Select a Choice", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (response2 == JOptionPane.YES_OPTION) {
                        JPanel panel = new JPanel();
                        JLabel details = new JLabel("Edit Details");
                        Font titleFont = new Font("Segoe UI", Font.PLAIN, 24);
                        details.setFont(titleFont);
                        JLabel articleName = new JLabel("Article Name");
                        JTextField articleNameTf = new JTextField();
                        articleNameTf.setText(ArticleName);
                        JLabel articleBrand = new JLabel("Article Brand");
                        JTextField articleBrandTf = new JTextField();
                        articleBrandTf.setText(BrandName);
                        JLabel date = new JLabel("Lost Date");
                        JTextField dateTf = new JTextField();
                        dateTf.setText(Date);
                        JLabel LostLocation = new JLabel("Lost Location");
                        JTextField LostLocationTf = new JTextField();
                        LostLocationTf.setText(Location);
                        JLabel Name = new JLabel("Your Name");
                        JTextField NameTf = new JTextField();
                        NameTf.setText(pName);
                        LostLocationTf.setText(Location);
                        JLabel Number = new JLabel("Your Phone Number");
                        JTextField NumberTf = new JTextField();
                        NumberTf.setText(mNumber);
                        LostLocationTf.setText(Location);
                        panel.add(details);
                        panel.add(articleName);
                        panel.add(articleNameTf);
                        panel.add(articleBrand);
                        panel.add(articleBrandTf);
                        panel.add(date);
                        panel.add(dateTf);
                        panel.add(LostLocation);
                        panel.add(LostLocationTf);
                        panel.add(Name);
                        panel.add(NameTf);
                        panel.add(Number);
                        panel.add(NumberTf);

                        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));

                        String[] options = new String[]{"OK", "Cancel"};
                        int option = JOptionPane.showOptionDialog(this, panel, "Edit Details",
                                JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                                null, options, options[1]);

                        String nArticleName = articleNameTf.getText();
                        String nArticleBrand = articleBrandTf.getText();
                        String nDate = dateTf.getText();
                        String nLocation = LostLocationTf.getText();
                        String nName = NameTf.getText();
                        String nNumber = NumberTf.getText();
                        long randID = System.currentTimeMillis();
                        int a = 0;
                        for (int i = 0; i < 4; i++) {
                            a = a * 10 + new Random().nextInt(100);
                        }
                        randID /= a;

                        String addQuery = "Insert into FoundItems values (" + randID + ",'" + nArticleName + "','" + nArticleBrand + "','" + Category + "','" + nDate + "','" + nLocation + "','" + nName + "'," + nNumber + ")";

                        System.out.println(addQuery);

                        statement.executeUpdate(addQuery);
                        JOptionPane.showMessageDialog(null, "You will be notified if the owner is found on your number " + nNumber + " .Note down your ItemId:  " + randID);

                    }
                }
            } else {
                String articleName = rs.getString("ArticleName");
                listModel.addElement(articleName);
                while (rs.next()) {
                    articleName = rs.getString("ArticleName");
                    listModel.addElement(articleName);
                }

                ResultList.setModel(listModel);
                ResultList.setEnabled(true);
                ConfirmButton.setEnabled(false);

                rs.close();
                statement.close();
                conn.close();
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReportFound.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ReportFound.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void ResultListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ResultListValueChanged
        // TODO add your handling code here:
        String ArticleName = ResultList.getSelectedValue();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String uid = "root";
            String pwd = "clever";
            String dbURL = "jdbc:mysql://localhost/getitback";
            Connection conn = DriverManager.getConnection(dbURL, uid, pwd);
            Statement statement = conn.createStatement();

            String query = "Select * from LostItems where ArticleName like '%"+ArticleName+"%'";
            
            ResultSet rs = statement.executeQuery(query);
            rs.next();
            String articleName = rs.getString("ArticleName");
            String articleBrand = rs.getString("ArticleBrand");
            String category = rs.getString("Category");
            String LostDate = rs.getString("LostDate");
            String LostLocation = rs.getString("LostLocation");
            String PersonToContact = rs.getString("PersonToContact");
            String ContactNumber = rs.getString("ContactNumber");
            
            jTextArea1.setText("");
            
            jTextArea1.append("Name: " + articleName+ "\n");
            jTextArea1.append("Article Brand: "+articleBrand + "\n");
            jTextArea1.append("Category:" + category + "\n");
            jTextArea1.append("Lost Date: "+LostDate +"\n");
            jTextArea1.append("Lost Location: "+LostLocation+"\n");
            
            ConfirmButton.setEnabled(true);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReportFound.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ReportFound.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_ResultListValueChanged

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Do you confirm of having the item?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {
            System.out.println("No button clicked");
        } else if (response == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "The Owner of Items is "+ person + ". Contact Number:" + pnumber);
        } else if (response == JOptionPane.CLOSED_OPTION) {
            System.out.println("JOptionPane closed");
        }
        
        
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        BrandNameTf.setText("");
        CategoryCB.setSelectedIndex(0);
        ConfirmButton.setEnabled(false);
        DateTf.setText("");
        LocationTf.setText("");
        NameTf.setText("");
        DefaultListModel listModel = new DefaultListModel();
        ResultList.setModel(listModel);
        articleNameTf.setText("");
        mNumberTf.setText("");
        person = "";
        pnumber = "";
    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportFound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportFound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportFound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportFound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportFound().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BrandNameTf;
    private javax.swing.JComboBox<String> CategoryCB;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JTextField DateTf;
    private javax.swing.JTextField LocationTf;
    private javax.swing.JTextField NameTf;
    private javax.swing.JButton Reset;
    private javax.swing.JList<String> ResultList;
    private javax.swing.JTextField articleNameTf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField mNumberTf;
    // End of variables declaration//GEN-END:variables
}
